### ISSUE TITLE
Trinket data from ItemSparse doesn't math correctly

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#105]
ItemSparse says item 142166 has 1557 agility and 1557 mastery. There's a multiplier in the combat ratings table for trinkets that should only apply to secondary stats. For item level 875 that multiplier is 0.658030492.

1557 * 0.658030492 = 1024.553476044

According to Wowhead (and the API), an 875 version of that trinket has 1634 agility and 1075 mastery. There has to be some sort of other multiplier that we're missing here. If you expand a little bit more and divide the value from the math above by the value that the stat should be, you get:

1557 / 1634 = 0.952876376988984
1024 / 1075 = 0.953073000971163

Those two values are close enough together to be a multiplier, but we can't figure out where the hell it comes from.

**Comment by confusingbits** [comment]
should have been addressed in https://github.com/ShadowCraft/shadowcraft-ui-react/commit/40ff0f950a0fd395ddbbc20b39848f3b852d63b5
