### ISSUE TITLE
changing the ilvl of a lego leads to an absurd dps/ilvl

### ISSUE THREAD

**Issue by confusingbits** [timwoj/shadowcraft-ui-python#112]

**Comment by timwoj** [comment]
The ilvl picker for legendaries is busted anyways:

![capture](https://user-images.githubusercontent.com/2653616/33972969-941b51d4-e03d-11e7-8ba0-0805bbcdcb5a.PNG)

We're only supposed to be showing 970 and 1000 there, and instead we're showing two versions of 970 and a 940.

**Comment by timwoj** [comment]
Fixed in a couple commits.
