### ISSUE TITLE
Reworking data layout

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#13]
An item's data in the database currently looks like this:

`{ "remote_id" : 121310, "item_level" : 875, "properties" : { "name" : "Nightmare Thorn", "upgradable" : false, "quality" : 4, "equip_location" : 12, "icon" : "inv_shield_draenorquest95_b_01", "armor_class" : "None", "stats" : { "agility" : 1634 }, "chance_bonus_lists" : [ 1808, 40, 41, 42, 1808, 603, 604, 605, 607 ], "socket_count" : 0 }, "is_gem" : false, "contexts" : [ "challenge-mode-3" ], "context_map" : { "challenge-mode-3" : { "tag" : " Mythic 4", "defaultBonuses" : [ 3412 ] } }, "socket_count" : 0 }`

There's an entry for each base item level with the contexts that have that same item level. I'd like to combine all of the entries for a single item into a single entry in the database, but I can't decide how to lay it out. I think the easiest thing is to move everything out of the `properties` dict into the main dict, and add an extra dict that maps from item level to a set of stats for each. This would end up looking something like below.

```
{
   "remote_id":121310,
   "name":"Nightmare Thorn",
   "upgradable":false,
   "quality":4,
   "equip_location":12,
   "icon":"inv_shield_draenorquest95_b_01",
   "armor_class":"None",
   "chance_bonus_lists":[1808, 40, 41, 42, 603, 604, 605, 607],
   "socket_count":0,
   "is_gem":false,
   "item_levels":{
      "865":{
         "stats":{
            "agility":1489
         },
         "contexts":[
            {
               "dungeon-mythic":{
                  "tag":"Mythic",
                  "defaultBonuses":[
                     1727
                  ]
               }
            }
         ]
      },
      "875":{
         "stats":{
            "agility":1634
         },
         "contexts":[
            {
               "challenge-mode-3":{
                  "tag":"Mythic 4",
                  "defaultBonuses":[
                     3412
                  ]
               }
            }
         ]
      }
   }
}
```

That makes it easier for the UI to just grab all of a single item and loop through the different item levels. The problem I run into is how to handle gems since they're items. My initial thought is that I could just use the same layout, but return a single "item level" for each gem that defines what it looks like. That way we could use the same popup for gems as for items, and reuse most of the code in the UI.

**Comment by timwoj** [comment]
Updated based on Discord discussion:

```
{
   "remote_id":121310,
   "name":"Nightmare Thorn",
   "upgradable":false,
   "quality":4,
   "equip_location":12,
   "icon":"inv_shield_draenorquest95_b_01",
   "armor_class":"None",
   "chance_bonus_lists":[1808, 40, 41, 42, 603, 604, 605, 607],
   "socket_count":0,
   "is_gem":false,
   "item_stats":{
      "865": {
            "agility":1489
      },
      "875":{
            "agility":1634
      }
   }
}
```

Next question is whether we should interpolate all of the missing stat blocks here in the python code as they're imported, or if we can just lean on the users' computers to do it as needed.

**Comment by confusingbits** [comment]
We can try outputting to the static file, and importing it into the js bundle. I don't think that the permutations will cost much in the browser, it's really the rendering that costs so much, and we can limit rendering too many permutations, especially on the initial popup with some cleverness if needed.

**Comment by timwoj** [comment]
The compression of an item down to a single entry alone would reduce the data considerably, to the point that I don't feel as bad about loading a static file with all of the items in it. It's still not my favorite solution, but it's not the  ridiculousness that exists on the live site.

**Comment by timwoj** [comment]
Demo output from testing:

```
{
   'remote_id':121310,
   'is_gem':False,
   'name':'Nightmare Thorn',
   'upgradable':False,
   'quality':3,
   'equip_location':12,
   'icon':'inv_shield_draenorquest95_b_01',
   'armor_class':'None',
   'chance_bonus_lists':[ 40, 41, 42, 1808, 603, 604, 605, 607 ],
   'socket_count':0,
   'item_stats':{
      '810':{ 'agility':868 },
      '825':{ 'agility':1026 },
      '845':{ 'agility':1236 },
      '870':{ 'agility':1560 },
      '865':{ 'agility':1489 },
      '875':{ 'agility':1634 }
   }
}
```

```
{
   'remote_id':128870,
   'is_gem':False,
   'name':'The Kingslayers',
   'upgradable':False,
   'quality':6,
   'equip_location':21,
   'icon':'inv_knife_1h_artifactgarona_d_01',
   'chance_bonus_lists':[ ],
   'speed':1.8,
   'dps':712.7778,
   'subclass':15,
   'socket_count':2,
   'item_stats':{
      '750':{
         'crit':148,
         'mastery':142,
         'agility':219,
         'stamina':328,
         'speed':1.8,
         'dps':712.7778
      }
   }
}
```

**Comment by timwoj** [comment]
Here's a gem:

```
{
   'remote_id':130222,
   'is_gem':True,
   'name':'Masterful Shadowruby',
   'quality':3,
   'icon':'inv_jewelcrafting_70_cutgem03_purple',
   'gem_slot':'Prismatic',
   'stats':{
      'mastery':150
   }
}
```
