### ISSUE TITLE
Replace current gear picker with a stack ranking

### ISSUE THREAD

**Issue by timwoj** [timwoj/shadowcraft-ui-python#78]
The current gear picker leaves a lot to be desired. The new stack rankings being seen in other places (such as the rogue TC site) is likely a better way.

**Comment by timwoj** [comment]
Here's one possible implementation:

![untitled](https://user-images.githubusercontent.com/2653616/31626556-06bd0cee-b25f-11e7-8338-efa85e423ffb.png)

**Comment by timwoj** [comment]
I was sitting here bored thinking about the implementation of this and had some questions:
- Do we want to only return items with ilvls > some minimum? I think HeroDamage only displays items above 900, which can obviously be any item, but we don't need to display any ilvls below that.
- It would be good if we could somehow page in this information instead of building it all at once for display. The current gear pickers are pretty fast now, but expanding the amount of data to return all ilvls in 5-step increments for every item is going to slow it down. If we were to page in the data, say only display the first 20 items, and then page in the rest as the user scrolls that might be faster. I'm not sure how we'd do that with the current item infrastructure tho.

**Comment by confusingbits** [comment]
One optimization might be to build them in webworkers, so that they don't block the main thread. But I don't think building the object is that expensive, just building the components took most of the time for the earlier tests. I don't know if you can prerender in webworkers and simple toggle display in the browser or not.

**Comment by timwoj** [comment]
How would that work? Create a set of workers that builds all of the items and does the calculations for them, and then popup the dialog when all of them are finished?

**Comment by confusingbits** [comment]
Would just rebuild them as stat weights change, so they are ready to go by the time the user click to open a popup.

**Comment by timwoj** [comment]
Started working on this on the `stack-ranking` branch. Building the actual items wasn't hard at all, but it gives some weird results. I requested items from 900 to 985, but I got back more than a few items at 990-1000. Either way generating the items themselves is fairly fast and I'm not concerned about that part now.

The next step is to change how the items are returned so that you get back a object indexed by item ID that maps to all of the items for that ID. This is so that we can display all of the items for each ID as a block instead of having to jump around.

**Comment by timwoj** [comment]
More thoughts on implementation:
- Generating all of the head item variants from 900 to the max takes 35ms on my machine. I don't think the time spent generating them is a concern at all.
- Item variant code should probably return an array of items as it was before, but let each item in there contain the set of variants. This lets us do a few things. First, the items are self-contained which means we can write a component that just takes the item including all of its variants and draws the row all at once. Second, if the variants in each item are ordered by item level, we can take the last variant of each item, do the EP calculation on it, and that takes care of the ranking of the stack itself. This shouldn't be too big of a stretch from how I already have it.

**Comment by timwoj** [comment]
> Item variant code should probably return an array of items as it was before, but let each item in there contain the set of variants. 

On second thought, it's probably best to just return an array of array of items. Combining the variants together into single items like suggested above just makes everything else harder because you have to break them apart again for the item selection, etc. An array of arrays of items, sorted by item level in the inner array and by item ID in the outer array would be good enough. I'm not super concerned about memory usage.

**Comment by timwoj** [comment]
All of the framework is in place with regards to items. It just needs UI work now.
