### ISSUE TITLE
Feature status

### ISSUE THREAD

**Issue by confusingbits** [timwoj/shadowcraft-ui-python#9]
- [x] Character input

  - [ ] Default race in settings to character race if new character

- [x] Gear Pane

  - [x] Gear Picker

  - [x] Item selection filter

  - [x] Modify Bonuses popup

  - [ ] Optimize Buttons

  - [x] Refresh button

- [x] Talent Pane

- [x] Artifact Pane

  - [x] Update stats/weapon on relic change

- [x] Advanced Pane

- [ ]  Right Pane

  - [x] +/- DPS on the readout

  - [ ] Notifications

  - [x] Capitalization

  - [x] History graph

- [x] Tooltips (ugh)

**Comment by timwoj** [comment]
Closing this in favor of the individual issues for the last few things.
